Added CI estimation for regression parameters and its visualization
cogstat/cogstat pull request #184
Opened 2022-05-24 15:51 UTC by TomiSzucs

2022-05-26 11:04 UTC, krajcsi requested changes
Looks promising!

2022-05-27 12:04 UTC, TomiSzucs commented on cogstat/cogstat_stat.py
> +    slope : Slope of the regression line
Added parameter types.

2022-05-27 12:36 UTC, krajcsi commented on cogstat/cogstat_chart.py
> +                # ax.scatter(data[x], data[y], color=theme_colors[0], marker='o')
```suggestion
                # this version in the comment would not make number pairs with multiple cases larger
                # ax.scatter(data[x], data[y], color=theme_colors[0], marker='o')
```

2022-05-27 12:38 UTC, krajcsi approved these changes
Looks great, thank you!

2022-05-27 12:40 UTC, merged