Added function for MR hypothesis tests
cogstat/cogstat pull request #205
Opened 2022-07-09 13:12 UTC by TomiSzucs

2022-07-11 12:38 UTC, krajcsi requested changes
Looks good mostly!

2022-07-11 12:38 UTC, krajcsi commented on cogstat/cogstat_hyp_test.py
> +    x : list of str
please, use another variable name

does the function work with one regressor? If so, please, extend the docstring. If not, please extend the code and the docstring :)

2022-07-11 12:38 UTC, krajcsi commented on cogstat/cogstat_hyp_test.py
> +    data : pandas dataframe
please, use this as the first parameter

2022-07-11 12:38 UTC, krajcsi commented on cogstat/cogstat_hyp_test.py
> +    html text
```suggestion
    str
        html text
```

2022-08-22 13:46 UTC, TomiSzucs commented on cogstat/cogstat_hyp_test.py
> +    data : pandas dataframe
Parameter "data" is now first in line.

2022-08-30 09:31 UTC, krajcsi commented
Looks good, thank you!

2022-08-30 09:34 UTC, merged