Reliability analysis fixes
cogstat/cogstat pull request #224
Opened 2023-01-30 13:01 UTC by TomiSzucs

- Visuals in internal consistency reliabiltiy analysis now show reverse items accordingly
- JASP validation added for Cronbach's alpha CI
- Formatting and text fixes

2023-01-30 14:11 UTC, krajcsi requested changes
Thanks for the fixes! Please, check the reversing method

2023-01-30 15:10 UTC, TomiSzucs commented on cogstat/cogstat.py
> +            data = data.copy()
It was added in a previous version of the code to solve an error I encountered. I tested it now, and indeed it is no longer needed and I deleted it.

2023-01-30 15:10 UTC, TomiSzucs commented on cogstat/cogstat_stat.py
>      Calculate internal consistency reliability using Cronbach's alpha and its confidence interval.
Added to the docstring of the function for clarity.

2023-01-30 15:11 UTC, TomiSzucs commented on cogstat/cogstat_stat.py
> +    pop_result_df['CI95%'] = [['%0.3f, %0.3f' % (ci[0], ci[1])] for ci in pop_result_df['CI95%']]
Indeed, it does :)

2023-02-10 13:28 UTC, krajcsi commented
Great, thanks for the fixes!

2023-02-10 13:28 UTC, merged